{
  "checkpoints": [
    "{\n  \"stub\": false,\n  \"trainable_name\": \"PPO\",\n  \"trial_id\": \"944e8_00000\",\n  \"config\": {\n    \"env\": \"my_env\",\n    \"num_gpus\": 0,\n    \"num_workers\": 1,\n    \"num_envs_per_worker\": 1,\n    \"gamma\": 1.0,\n    \"rollout_fragment_length\": 600,\n    \"vf_clip_param\": 200,\n    \"framework\": \"torch\",\n    \"ignore_worker_failures\": true,\n    \"callbacks\": {\n      \"_type\": \"CLOUDPICKLE_FALLBACK\",\n      \"value\": \"80059551060000000000008c1b7261792e636c6f75647069636b6c652e636c6f75647069636b6c65948c145f6d616b655f736b656c65746f6e5f636c617373949394288c086275696c74696e73948c04747970659493948c0b4d7943616c6c6261636b73948c1a7261792e726c6c69622e6167656e74732e63616c6c6261636b73948c1044656661756c7443616c6c6261636b7394939485947d948c203866393535313064653732363462643038656532656635323634363535346234944e749452948c207261792e636c6f75647069636b6c652e636c6f75647069636b6c655f66617374948c0f5f636c6173735f7365747374617465949394680e7d94288c0a5f5f6d6f64756c655f5f948c085f5f6d61696e5f5f948c106f6e5f657069736f64655f73746172749468008c0d5f6275696c74696e5f747970659493948c0a4c616d6264615479706594859452942868178c08436f6465547970659485945294284b014b004b054b074b034b4b434067007c046a0064013c0067007c046a0064023c0067007c046a0064033c0067007c046a0064043c0067007c046a0064053c0067007c046a0064063c006400530094284e8c08636f6e7374616e74948c0d7765696768745f726577617264948c086578706f73757265948c16706f7369746976655f7765696768745f726577617264948c0b657069736f64655f6e756d948c08737465705f6e756d9474948c09686973745f64617461948594288c0473656c66948c06776f726b6572948c08626173655f656e76948c08706f6c6963696573948c07657069736f6465948c09656e765f696e646578948c066b77617267739474948cb9633a2f55736572732f32383432302f4465736b746f702f534149432f44656e73652d446565702d5265696e666f7263656d656e742d4c6561726e696e672d6d61696e2f73756d6f5f646174615f6d657267655f3430305f686967687761795f676c6f62616c5f696e666f5f726f61645f73747275635f6167656e745f747261696e2f747261696e5f6167656e745f6d657267655f3430305f686967687761795f676c6f62616c5f696e666f5f726f61645f73747275632e7079948c106f6e5f657069736f64655f7374617274944b29430c00030a010a010a010a010a01942929749452947d94288c0b5f5f7061636b6167655f5f944e8c085f5f6e616d655f5f9468148c085f5f66696c655f5f946830754e4e4e74945294680f8c125f66756e6374696f6e5f7365747374617465949394683a7d947d9428683768318c0c5f5f7175616c6e616d655f5f948c1c4d7943616c6c6261636b732e6f6e5f657069736f64655f7374617274948c0f5f5f616e6e6f746174696f6e735f5f947d94288c06776f726b6572948c0d526f6c6c6f7574576f726b6572948c08626173655f656e76948c167261792e726c6c69622e656e762e626173655f656e76948c0742617365456e769493948c08706f6c6963696573948c095f6f70657261746f72948c076765746974656d9493948c06747970696e67948c044469637494939468038c037374729493948c177261792e726c6c69622e706f6c6963792e706f6c696379948c06506f6c6963799493948694869452948c07657069736f6465948c1c7261792e726c6c69622e6576616c756174696f6e2e657069736f6465948c114d756c74694167656e74457069736f64659493948c09656e765f696e6465789468038c03696e74949394758c0e5f5f6b7764656661756c74735f5f944e8c0c5f5f64656661756c74735f5f944e681368148c075f5f646f635f5f944e8c0b5f5f636c6f737572655f5f944e8c175f636c6f75647069636b6c655f7375626d6f64756c6573945d948c0b5f5f676c6f62616c735f5f947d947586948652308c0e6f6e5f657069736f64655f656e6494681a28681d284b014b004b054b084b024b4b430c7c04a000a1007d0764005300944e85948c0d6c6173745f696e666f5f666f729485942868286829682a682b682c682d682e8c096c6173745f696e666f94749468308c0e6f6e5f657069736f64655f656e64944b33430200029429297494529468354e4e4e74945294683c68747d947d94286837686f683f8c1a4d7943616c6c6261636b732e6f6e5f657069736f64655f656e649468417d94286843684468456848684968576858685b685c685e75685f4e68604e6813681468614e68624e68635d9468657d9475869486523068614e757d9486948652302e\"\n    },\n    \"model\": {\n      \"use_lstm\": true,\n      \"max_seq_len\": 20,\n      \"lstm_cell_size\": 256,\n      \"lstm_use_prev_action\": false,\n      \"lstm_use_prev_reward\": false,\n      \"_time_major\": false\n    }\n  },\n  \"local_dir\": \"E:\\\\pycharmcode\\\\sumo_data_generation\\\\400m_merge_global_info_struc_Agent_Training\",\n  \"evaluated_params\": {},\n  \"experiment_tag\": \"0\",\n  \"location\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"8005953a000000000000008c0e7261792e74756e652e747269616c948c084c6f636174696f6e9493942981947d94288c08686f73746e616d65944e8c03706964944e75622e\"\n  },\n  \"placement_group_factory\": \"800595b5000000000000008c1f7261792e74756e652e7574696c732e706c6163656d656e745f67726f757073948c15506c6163656d656e7447726f7570466163746f72799493942981947d94288c085f62756e646c6573945d94287d948c0343505594473ff0000000000000737d946808473ff000000000000073658c155f686561645f62756e646c655f69735f656d70747994898c095f7374726174656779948c045041434b948c055f6172677394298c075f6b7761726773947d9475622e\",\n  \"stopping_criterion\": {\n    \"training_iteration\": 1000\n  },\n  \"log_to_file\": [\n    null,\n    null\n  ],\n  \"max_failures\": 0,\n  \"_last_result\": {},\n  \"_default_result_or_future\": null,\n  \"last_update_time\": -Infinity,\n  \"metric_analysis\": {},\n  \"n_steps\": [\n    5,\n    10\n  ],\n  \"metric_n_steps\": {},\n  \"export_formats\": [],\n  \"status\": \"ERROR\",\n  \"start_time\": 1719907844.0595076,\n  \"logdir\": \"E:\\\\pycharmcode\\\\sumo_data_generation\\\\400m_merge_global_info_struc_Agent_Training\\\\PPO_my_env_944e8_00000_0_2024-07-02_16-10-44\",\n  \"runner\": null,\n  \"last_debug\": 0,\n  \"error_file\": \"E:\\\\pycharmcode\\\\sumo_data_generation\\\\400m_merge_global_info_struc_Agent_Training\\\\PPO_my_env_944e8_00000_0_2024-07-02_16-10-44\\\\error.txt\",\n  \"error_msg\": \"Traceback (most recent call last):\\n  File \\\"C:\\\\Users\\\\28420\\\\AppData\\\\Roaming\\\\Python\\\\Python38\\\\site-packages\\\\ray\\\\tune\\\\trial_runner.py\\\", line 886, in _process_trial\\n    results = self.trial_executor.fetch_result(trial)\\n  File \\\"C:\\\\Users\\\\28420\\\\AppData\\\\Roaming\\\\Python\\\\Python38\\\\site-packages\\\\ray\\\\tune\\\\ray_trial_executor.py\\\", line 675, in fetch_result\\n    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\\n  File \\\"C:\\\\Users\\\\28420\\\\AppData\\\\Roaming\\\\Python\\\\Python38\\\\site-packages\\\\ray\\\\_private\\\\client_mode_hook.py\\\", line 105, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"C:\\\\Users\\\\28420\\\\AppData\\\\Roaming\\\\Python\\\\Python38\\\\site-packages\\\\ray\\\\worker.py\\\", line 1763, in get\\n    raise value.as_instanceof_cause()\\nray.exceptions.RayTaskError(RuntimeError): \\u001b[36mray::PPOTrainer.train()\\u001b[39m (pid=6204, ip=127.0.0.1, repr=PPOTrainer)\\n  File \\\"C:\\\\Users\\\\28420\\\\AppData\\\\Roaming\\\\Python\\\\Python38\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\28420\\\\AppData\\\\Roaming\\\\Python\\\\Python38\\\\site-packages\\\\ray\\\\rllib\\\\agents\\\\trainer.py\\\", line 1044, in step_attempt\\n    step_results = self._exec_plan_or_training_iteration_fn()\\n  File \\\"C:\\\\Users\\\\28420\\\\AppData\\\\Roaming\\\\Python\\\\Python38\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\28420\\\\AppData\\\\Roaming\\\\Python\\\\Python38\\\\site-packages\\\\ray\\\\rllib\\\\agents\\\\trainer.py\\\", line 2032, in _exec_plan_or_training_iteration_fn\\n    results = next(self.train_exec_impl)\\n  File \\\"C:\\\\Users\\\\28420\\\\AppData\\\\Roaming\\\\Python\\\\Python38\\\\site-packages\\\\ray\\\\util\\\\iter.py\\\", line 756, in __next__\\n    return next(self.built_iterator)\\n  File \\\"C:\\\\Users\\\\28420\\\\AppData\\\\Roaming\\\\Python\\\\Python38\\\\site-packages\\\\ray\\\\util\\\\iter.py\\\", line 783, in apply_foreach\\n    for item in it:\\n  File \\\"C:\\\\Users\\\\28420\\\\AppData\\\\Roaming\\\\Python\\\\Python38\\\\site-packages\\\\ray\\\\util\\\\iter.py\\\", line 783, in apply_foreach\\n    for item in it:\\n  File \\\"C:\\\\Users\\\\28420\\\\AppData\\\\Roaming\\\\Python\\\\Python38\\\\site-packages\\\\ray\\\\util\\\\iter.py\\\", line 843, in apply_filter\\n    for item in it:\\n  File \\\"C:\\\\Users\\\\28420\\\\AppData\\\\Roaming\\\\Python\\\\Python38\\\\site-packages\\\\ray\\\\util\\\\iter.py\\\", line 843, in apply_filter\\n    for item in it:\\n  File \\\"C:\\\\Users\\\\28420\\\\AppData\\\\Roaming\\\\Python\\\\Python38\\\\site-packages\\\\ray\\\\util\\\\iter.py\\\", line 783, in apply_foreach\\n    for item in it:\\n  File \\\"C:\\\\Users\\\\28420\\\\AppData\\\\Roaming\\\\Python\\\\Python38\\\\site-packages\\\\ray\\\\util\\\\iter.py\\\", line 783, in apply_foreach\\n    for item in it:\\n  File \\\"C:\\\\Users\\\\28420\\\\AppData\\\\Roaming\\\\Python\\\\Python38\\\\site-packages\\\\ray\\\\util\\\\iter.py\\\", line 783, in apply_foreach\\n    for item in it:\\n  [Previous line repeated 1 more time]\\n  File \\\"C:\\\\Users\\\\28420\\\\AppData\\\\Roaming\\\\Python\\\\Python38\\\\site-packages\\\\ray\\\\util\\\\iter.py\\\", line 876, in apply_flatten\\n    for item in it:\\n  File \\\"C:\\\\Users\\\\28420\\\\AppData\\\\Roaming\\\\Python\\\\Python38\\\\site-packages\\\\ray\\\\util\\\\iter.py\\\", line 783, in apply_foreach\\n    for item in it:\\n  File \\\"C:\\\\Users\\\\28420\\\\AppData\\\\Roaming\\\\Python\\\\Python38\\\\site-packages\\\\ray\\\\util\\\\iter.py\\\", line 783, in apply_foreach\\n    for item in it:\\n  File \\\"C:\\\\Users\\\\28420\\\\AppData\\\\Roaming\\\\Python\\\\Python38\\\\site-packages\\\\ray\\\\util\\\\iter.py\\\", line 783, in apply_foreach\\n    for item in it:\\n  [Previous line repeated 1 more time]\\n  File \\\"C:\\\\Users\\\\28420\\\\AppData\\\\Roaming\\\\Python\\\\Python38\\\\site-packages\\\\ray\\\\util\\\\iter.py\\\", line 471, in base_iterator\\n    yield ray.get(futures, timeout=timeout)\\n  File \\\"C:\\\\Users\\\\28420\\\\AppData\\\\Roaming\\\\Python\\\\Python38\\\\site-packages\\\\ray\\\\_private\\\\client_mode_hook.py\\\", line 105, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"C:\\\\Users\\\\28420\\\\AppData\\\\Roaming\\\\Python\\\\Python38\\\\site-packages\\\\ray\\\\worker.py\\\", line 1763, in get\\n    raise value.as_instanceof_cause()\\nray.exceptions.RayTaskError(ValueError): \\u001b[36mray::RolloutWorker.par_iter_next()\\u001b[39m (pid=7612, ip=127.0.0.1, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x0000023CCD7A7910>)\\n  File \\\"python\\\\ray\\\\_raylet.pyx\\\", line 640, in ray._raylet.execute_task\\n  File \\\"python\\\\ray\\\\_raylet.pyx\\\", line 644, in ray._raylet.execute_task\\n  File \\\"python\\\\ray\\\\_raylet.pyx\\\", line 593, in ray._raylet.execute_task.function_executor\\n  File \\\"C:\\\\Users\\\\28420\\\\AppData\\\\Roaming\\\\Python\\\\Python38\\\\site-packages\\\\ray\\\\_private\\\\function_manager.py\\\", line 648, in actor_method_executor\\n    return method(__ray_actor, *args, **kwargs)\\n  File \\\"C:\\\\Users\\\\28420\\\\AppData\\\\Roaming\\\\Python\\\\Python38\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\28420\\\\AppData\\\\Roaming\\\\Python\\\\Python38\\\\site-packages\\\\ray\\\\util\\\\iter.py\\\", line 1151, in par_iter_next\\n    return next(self.local_it)\\n  File \\\"C:\\\\Users\\\\28420\\\\AppData\\\\Roaming\\\\Python\\\\Python38\\\\site-packages\\\\ray\\\\rllib\\\\evaluation\\\\rollout_worker.py\\\", line 380, in gen_rollouts\\n    yield self.sample()\\n  File \\\"C:\\\\Users\\\\28420\\\\AppData\\\\Roaming\\\\Python\\\\Python38\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\28420\\\\AppData\\\\Roaming\\\\Python\\\\Python38\\\\site-packages\\\\ray\\\\rllib\\\\evaluation\\\\rollout_worker.py\\\", line 759, in sample\\n    batches = [self.input_reader.next()]\\n  File \\\"C:\\\\Users\\\\28420\\\\AppData\\\\Roaming\\\\Python\\\\Python38\\\\site-packages\\\\ray\\\\rllib\\\\evaluation\\\\sampler.py\\\", line 104, in next\\n    batches = [self.get_data()]\\n  File \\\"C:\\\\Users\\\\28420\\\\AppData\\\\Roaming\\\\Python\\\\Python38\\\\site-packages\\\\ray\\\\rllib\\\\evaluation\\\\sampler.py\\\", line 266, in get_data\\n    item = next(self._env_runner)\\n  File \\\"C:\\\\Users\\\\28420\\\\AppData\\\\Roaming\\\\Python\\\\Python38\\\\site-packages\\\\ray\\\\rllib\\\\evaluation\\\\sampler.py\\\", line 634, in _env_runner\\n    _process_observations(\\n  File \\\"C:\\\\Users\\\\28420\\\\AppData\\\\Roaming\\\\Python\\\\Python38\\\\site-packages\\\\ray\\\\rllib\\\\evaluation\\\\sampler.py\\\", line 852, in _process_observations\\n    prep_obs = preprocessor.transform(raw_obs)\\n  File \\\"C:\\\\Users\\\\28420\\\\AppData\\\\Roaming\\\\Python\\\\Python38\\\\site-packages\\\\ray\\\\rllib\\\\models\\\\preprocessors.py\\\", line 195, in transform\\n    self.check_shape(observation)\\n  File \\\"C:\\\\Users\\\\28420\\\\AppData\\\\Roaming\\\\Python\\\\Python38\\\\site-packages\\\\ray\\\\rllib\\\\models\\\\preprocessors.py\\\", line 72, in check_shape\\n    raise ValueError(\\nValueError: ('Observation ({} dtype={}) outside given space ({})!', array([ 23.264256 ,   1.8368307,  90.       ,   0.       , 305.50305  ,\\n         0.       ,  35.704857 ,  -1.196751 ,  90.       ,  37.92038  ,\\n       348.41876  ,   0.       ,  34.66982  ,  -1.1415881,  82.36437  ,\\n        85.29354  , 395.76212  ,   1.       ,   0.       ,   0.       ,\\n         0.       ,   0.       ,   0.       ,   0.       ,  24.856346 ,\\n         0.       ,  90.       ,  13.94338  , 286.56216  ,   0.       ,\\n        31.574991 ,  -1.3310364,  90.       ,  27.58276  , 272.88727  ,\\n         1.       ,   0.       ,   0.       ,   0.       ,   0.       ,\\n         0.       ,   0.       ], dtype=float32), dtype('float32'), Box([-200. -200. -200. -200. -200. -200. -200. -200. -200. -200. -200. -200.\\n -200. -200. -200. -200. -200. -200. -200. -200. -200. -200. -200. -200.\\n -200. -200. -200. -200. -200. -200. -200. -200. -200. -200. -200. -200.\\n -200. -200. -200. -200. -200. -200.], [200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200.\\n 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200.\\n 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200. 200.], (42,), float32))\\n\\nDuring handling of the above exception, another exception occurred:\\n\\n\\u001b[36mray::PPOTrainer.train()\\u001b[39m (pid=6204, ip=127.0.0.1, repr=PPOTrainer)\\n  File \\\"python\\\\ray\\\\_raylet.pyx\\\", line 633, in ray._raylet.execute_task\\n  File \\\"python\\\\ray\\\\_raylet.pyx\\\", line 674, in ray._raylet.execute_task\\n  File \\\"python\\\\ray\\\\_raylet.pyx\\\", line 640, in ray._raylet.execute_task\\n  File \\\"python\\\\ray\\\\_raylet.pyx\\\", line 644, in ray._raylet.execute_task\\n  File \\\"python\\\\ray\\\\_raylet.pyx\\\", line 593, in ray._raylet.execute_task.function_executor\\n  File \\\"C:\\\\Users\\\\28420\\\\AppData\\\\Roaming\\\\Python\\\\Python38\\\\site-packages\\\\ray\\\\_private\\\\function_manager.py\\\", line 648, in actor_method_executor\\n    return method(__ray_actor, *args, **kwargs)\\n  File \\\"C:\\\\Users\\\\28420\\\\AppData\\\\Roaming\\\\Python\\\\Python38\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\28420\\\\AppData\\\\Roaming\\\\Python\\\\Python38\\\\site-packages\\\\ray\\\\tune\\\\trainable.py\\\", line 319, in train\\n    result = self.step()\\n  File \\\"C:\\\\Users\\\\28420\\\\AppData\\\\Roaming\\\\Python\\\\Python38\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\28420\\\\AppData\\\\Roaming\\\\Python\\\\Python38\\\\site-packages\\\\ray\\\\rllib\\\\agents\\\\trainer.py\\\", line 972, in step\\n    self.try_recover_from_step_attempt()\\n  File \\\"C:\\\\Users\\\\28420\\\\AppData\\\\Roaming\\\\Python\\\\Python38\\\\site-packages\\\\ray\\\\util\\\\tracing\\\\tracing_helper.py\\\", line 451, in _resume_span\\n    return method(self, *_args, **_kwargs)\\n  File \\\"C:\\\\Users\\\\28420\\\\AppData\\\\Roaming\\\\Python\\\\Python38\\\\site-packages\\\\ray\\\\rllib\\\\agents\\\\trainer.py\\\", line 2434, in try_recover_from_step_attempt\\n    raise RuntimeError(\\nRuntimeError: Not enough healthy workers remain to continue.\\n\",\n  \"trial_name_creator\": null,\n  \"custom_trial_name\": null,\n  \"custom_dirname\": null,\n  \"saving_to\": null,\n  \"remote_checkpoint_dir_prefix\": null,\n  \"sync_function_tpl\": null,\n  \"checkpoint_freq\": 100,\n  \"checkpoint_at_end\": false,\n  \"keep_checkpoints_num\": null,\n  \"checkpoint_score_attr\": \"training_iteration\",\n  \"sync_on_checkpoint\": true,\n  \"checkpoint_manager\": {\n    \"_type\": \"CLOUDPICKLE_FALLBACK\",\n    \"value\": \"80059583010000000000008c1b7261792e74756e652e636865636b706f696e745f6d616e61676572948c11436865636b706f696e744d616e616765729493942981947d94288c146b6565705f636865636b706f696e74735f6e756d94477ff00000000000008c165f636865636b706f696e745f73636f72655f6465736394898c165f636865636b706f696e745f73636f72655f61747472948c12747261696e696e675f697465726174696f6e948c1c6e65776573745f70657273697374656e745f636865636b706f696e749468008c0a436865636b706f696e749493942981947d94288c0773746f72616765948c0a70657273697374656e74948c0576616c7565944e8c06726573756c74947d948c056f72646572944b0075628c195f6e65776573745f6d656d6f72795f636865636b706f696e7494680b2981947d9428680e8c066d656d6f72799468104e68117d9468134b0075628c115f626573745f636865636b706f696e7473945d948c0b5f6d656d62657273686970948f948c0a5f6375725f6f72646572944b0075622e\"\n  },\n  \"restore_path\": null,\n  \"restoring_from\": null,\n  \"num_failures\": 1,\n  \"has_new_resources\": false,\n  \"results\": \"80054e2e\",\n  \"best_result\": \"80054e2e\",\n  \"param_config\": \"80054e2e\",\n  \"extra_arg\": \"80054e2e\",\n  \"_state_json\": null,\n  \"_state_valid\": false\n}"
  ],
  "runner_data": {
    "_insufficient_resources_manager": {
      "_type": "CLOUDPICKLE_FALLBACK",
      "value": "8005958b000000000000008c277261792e74756e652e696e73756666696369656e745f7265736f75726365735f6d616e61676572948c1c496e73756666696369656e745265736f75726365734d616e616765729493942981947d94288c185f6e6f5f72756e6e696e675f747269616c735f73696e6365944affffffff8c0f5f6c6173745f747269616c5f6e756d944affffffff75622e"
    },
    "_max_pending_trials": 16,
    "_metric": null,
    "_total_time": 0,
    "_iteration": 2,
    "_has_errored": true,
    "_fail_fast": false,
    "_server_port": null,
    "_cached_trial_decisions": {},
    "_queued_trial_decisions": {},
    "_updated_queue": true,
    "_result_wait_time": 1,
    "_should_stop_experiment": false,
    "_local_checkpoint_dir": "E:\\pycharmcode\\sumo_data_generation\\400m_merge_global_info_struc_Agent_Training",
    "_remote_checkpoint_dir": null,
    "_stopper": {
      "_type": "CLOUDPICKLE_FALLBACK",
      "value": "80059527000000000000008c107261792e74756e652e73746f70706572948c0b4e6f6f7053746f707065729493942981942e"
    },
    "_resumed": false,
    "_start_time": 1719907843.8914516,
    "_last_checkpoint_time": -Infinity,
    "_session_str": "2024-07-02_16-10-43",
    "checkpoint_file": "E:\\pycharmcode\\sumo_data_generation\\400m_merge_global_info_struc_Agent_Training\\experiment_state-2024-07-02_16-10-43.json",
    "_checkpoint_period": "auto",
    "launch_web_server": false
  },
  "stats": {
    "start_time": 1719907843.8914516,
    "timestamp": 1719907844.0907497
  }
}